name: auto-release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Tag
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Display Tag
        run: echo "${{ steps.get_tag.outputs.tag }}"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get Recent Commit Tag
        id: get_commit_tag
        run: |
          COMMIT_TAG=$(git describe --tags --abbrev=0)
          echo "COMMIT_TAG=${COMMIT_TAG}" >> $GITHUB_ENV

      - name: Display Commit Tag
        run: |
          echo "Commit Tag: $COMMIT_TAG"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "awesomerelease-$COMMIT_TAG"
          generate_release_notes: true
