name: wget and echo
on:
  workflow_dispatch:
jobs:
  commitCheckJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: WGet my file
        uses: wei/wget@v1
        with:
          args: -O test.log https://noxplay.us.to/noxbackup/log

      - name: echo
        run: |
          sudo chmod 777 test.log
          echo "${{ secrets.TEST1 }}" > test.log
          echo "${{ secrets.TEST1 }}" > test.log

      - name: cat results
        id: vars
        run: |
          echo "content=$(cat test.log)" >> $GITHUB_OUTPUT

      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "wget"
          files: ./*.log
          target_commitish: ${{ env.GIT_BRANCH }}
